"""auto-vote

Revision ID: acb5cfa997eb
Revises: b509cab4ba10
Create Date: 2022-01-20 20:50:23.540923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb5cfa997eb'
down_revision = 'b509cab4ba10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
